# Generated by Django 5.2.7 on 2025-12-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_province_province_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('ai_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
